In [1]:
import pandas as pd
import numpy as np

In [2]:
# 불러오고 싶은 csv 파일의 열 이름만 저장하기
filename='서울교통공사_역별 일별 시간대별 승하차인원 정보_20230930.csv'
cols = pd.read_csv(filename, encoding='euc-kr', nrows=0).columns
cols

Index(['연번', '수송일자', '호선', '역번호', '역명', '승하차구분', '06시이전', '06-07시간대',
       '07-08시간대', '08-09시간대', '09-10시간대', '10-11시간대', '11-12시간대', '12-13시간대',
       '13-14시간대', '14-15시간대', '15-16시간대', '16-17시간대', '17-18시간대', '18-19시간대',
       '19-20시간대', '20-21시간대', '21-22시간대', '22-23시간대', '23-24시간대', '24시이후'],
      dtype='object')

In [3]:
# '연번' 제외한 열들 불러오기
seoulsubDF = pd.read_csv(filename, encoding='euc-kr', usecols=cols[1:])
seoulsubDF

,수송일자,호선,역번호,역명,승하차구분,06시이전,06-07시간대,07-08시간대,08-09시간대,09-10시간대,...,15-16시간대,16-17시간대,17-18시간대,18-19시간대,19-20시간대,20-21시간대,21-22시간대,22-23시간대,23-24시간대,24시이후
0,2023-01-01,1호선,150,서울역,승차,215,145,231,594,923,...,2655,2509,2696,2549,2462,2177,2190,1808,734,7
1,2023-01-01,1호선,150,서울역,하차,154,636,595,939,1306,...,2282,2295,2526,1930,1897,1487,991,609,280,46
2,2023-01-01,1호선,151,시청,승차,48,73,106,194,239,...,843,895,959,985,670,630,515,330,146,0
3,2023-01-01,1호선,151,시청,하차,64,247,293,463,522,...,602,575,533,456,285,267,246,154,79,18
4,2023-01-01,1호선,152,종각,승차,407,235,158,201,188,...,1145,1402,1223,1272,911,913,906,602,232,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148790,2023-09-30,8호선,2826,수진,하차,8,0,8,40,30,...,195,165,136,171,190,178,132,153,162,133
148791,2023-09-30,8호선,2827,모란,승차,39,0,39,34,54,...,200,189,205,233,219,169,103,137,117,105
148792,2023-09-30,8호선,2827,모란,하차,9,0,9,45,46,...,132,156,164,165,216,215,176,121,113,113
148793,2023-09-30,8호선,2828,남위례,승차,20,0,20,54,54,...,184,211,201,214,182,189,112,131,134,105
148794,2023-09-30,8호선,2828,남위례,하차,16,0,16,53,38,...,157,152,198,228,228,230,221,188,173,171

In [4]:
# 행 단위, 여러 열들의 합계 구하기
seoulsubDF.loc[:, '총합'] = seoulsubDF.loc[:, '06시이전':'24시이후'].sum(axis=1)
seoulsubDF

,수송일자,호선,역번호,역명,승하차구분,06시이전,06-07시간대,07-08시간대,08-09시간대,09-10시간대,...,16-17시간대,17-18시간대,18-19시간대,19-20시간대,20-21시간대,21-22시간대,22-23시간대,23-24시간대,24시이후,총합
0,2023-01-01,1호선,150,서울역,승차,215,145,231,594,923,...,2509,2696,2549,2462,2177,2190,1808,734,7,32023
1,2023-01-01,1호선,150,서울역,하차,154,636,595,939,1306,...,2295,2526,1930,1897,1487,991,609,280,46,27044
2,2023-01-01,1호선,151,시청,승차,48,73,106,194,239,...,895,959,985,670,630,515,330,146,0,9317
3,2023-01-01,1호선,151,시청,하차,64,247,293,463,522,...,575,533,456,285,267,246,154,79,18,8300
4,2023-01-01,1호선,152,종각,승차,407,235,158,201,188,...,1402,1223,1272,911,913,906,602,232,3,13019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148790,2023-09-30,8호선,2826,수진,하차,8,0,8,40,30,...,165,136,171,190,178,132,153,162,133,2101
148791,2023-09-30,8호선,2827,모란,승차,39,0,39,34,54,...,189,205,233,219,169,103,137,117,105,2562
148792,2023-09-30,8호선,2827,모란,하차,9,0,9,45,46,...,156,164,165,216,215,176,121,113,113,2175
148793,2023-09-30,8호선,2828,남위례,승차,20,0,20,54,54,...,211,201,214,182,189,112,131,134,105,2698
148794,2023-09-30,8호선,2828,남위례,하차,16,0,16,53,38,...,152,198,228,228,230,221,188,173,171,2640

In [6]:
count = seoulsubDF.shape[0]
count

148795

In [10]:
df_total_count_of_perople = seoulsubDF['총합']

stations = set()

for i in range(count):
    stations.add(seoulsubDF.iloc[i]['역명'])

dict_count_of_people_by_stations = dict()

for station in stations:
    dict_count_of_people_by_stations[station] = 0
print(dict_count_of_people_by_stations)

{'신정네거리': 0, '충정로(경기대입구)': 0, '마들': 0, '매봉': 0, '오목교(목동운동장앞)': 0, '서대문': 0, '강동구청': 0, '종각': 0, '마포': 0, '망원': 0, '마천': 0, '미아사거리': 0, '금호': 0, '증산(명지대앞)': 0, '하계': 0, '여의나루': 0, '학여울': 0, '미사': 0, '건대입구': 0, '하남검단산': 0, '역삼': 0, '거여': 0, '독바위': 0, '안암(고대병원앞)': 0, '신금호': 0, '구의(광진구청)': 0, '수유(강북구청)': 0, '동대문': 0, '용마산(용마폭포공원)': 0, '중곡': 0, '신대방삼거리': 0, '고속터미널': 0, '애오개': 0, '성신여대입구(돈암)': 0, '우장산': 0, '하남풍산': 0, '월곡(동덕여대)': 0, '춘의': 0, '사당': 0, '몽촌토성(평화의문)': 0, '까치울': 0, '도곡': 0, '장승배기': 0, '부천시청': 0, '개롱': 0, '한양대': 0, '불광': 0, '광화문(세종문화회관)': 0, '고덕': 0, '대치': 0, '경복궁(정부서울청사)': 0, '상수': 0, '신풍': 0, '천왕': 0, '송파': 0, '모란': 0, '용두(동대문구청)': 0, '장지': 0, '김포공항': 0, '신흥': 0, '신촌': 0, '합정': 0, '공릉(서울과학기술대)': 0, '용답': 0, '둔촌동': 0, '수서': 0, '광나루(장신대)': 0, '수진': 0, '송정': 0, '올림픽공원(한국체대)': 0, '문래': 0, '숭실대입구(살피재)': 0, '산성': 0, '내방': 0, '신대방': 0, '문정': 0, '서울역': 0, '대청': 0, '무악재': 0, '당고개': 0, '강동': 0, '가락시장': 0, '청구': 0, '성수': 0, '버티고개': 0, '동묘앞': 0, '방배': 0, '이촌(국립중앙박물관)': 0, '영등포시장': 0, '동대입구': 0, '잠실(송파구청)': 0, '구로디지털단지': 0, '양평': 0, '회현(남대문시장)': 0, '신당': 0, '남부터미널(예술의전당)': 0, '중화': 0, '잠원': 0, '발산': 0, '상왕십리': 0, '도림천': 0, '봉천': 0, '당산': 0, '봉화산(서울의료원)': 0, '종합운동장': 0, '길동': 0, '수락산': 0, '한성대입구(삼선교)': 0, '디지털미디어시티': 0, '왕십리(성동구청)': 0, '양천구청': 0, '고려대(종암)': 0, '남성': 0, '독립문': 0, '시청': 0, '강변(동서울터미널)': 0, '신정(은행정)': 0, '연신내': 0, '종로5가': 0, '낙성대(강감찬)': 0, '강남': 0, '태릉입구': 0, '응암': 0, '가산디지털단지': 0, '반포': 0, '암사': 0, '마장': 0, '약수': 0, '신용산': 0, '을지로3가': 0, '서울대입구(관악구청)': 0, '미아(서울사이버대학)': 0, '방이': 0, '충무로': 0, '신답': 0, '도봉산': 0, '석촌': 0, '옥수': 0, '일원': 0, '쌍문': 0, '구산': 0, '석계': 0, '개화산': 0, '지축': 0, '대림(구로구청)': 0, '중계': 0, '남위례': 0, '동대문역사문화공원(DDP)': 0, '먹골': 0, '청담': 0, '상도': 0, '신사': 0, '강남구청': 0, '동작(현충원)': 0, '면목': 0, '목동': 0, '녹번': 0, '보문': 0, '단대오거리': 0, '신도림': 0, '장암': 0, '종로3가': 0, '학동': 0, '삼성(무역센터)': 0, '행당': 0, '이태원': 0, '방화': 0, '강일': 0, '광흥창(서강)': 0, '화랑대(서울여대입구)': 0, '교대(법원.검찰청)': 0, '서초': 0, '상계': 0, '군자(능동)': 0, '오금': 0, '뚝섬유원지': 0, '숙대입구(갈월)': 0, '구파발': 0, '아현': 0, '역촌': 0, '철산': 0, '잠실나루': 0, '압구정': 0, '남태령': 0, '뚝섬': 0, '경찰병원': 0, '사가정': 0, '마포구청': 0, '이수': 0, '양재(서초구청)': 0, '보라매': 0, '혜화': 0, '총신대입구(이수)': 0, '대흥(서강대앞)': 0, '월드컵경기장(성산)': 0, '창동': 0, '명일': 0, '홍제': 0, '아차산(어린이대공원후문)': 0, '신내': 0, '이대': 0, '홍대입구': 0, '상일동': 0, '한강진': 0, '삼산체육관': 0, '제기동': 0, '신설동': 0, '잠실새내': 0, '영등포구청': 0, '노원': 0, '공덕': 0, '안국': 0, '돌곶이': 0, '을지로입구': 0, '상월곡(한국과학기술연구원)': 0, '마곡': 0, '상봉(시외버스터미널)': 0, '신림': 0, '굽은다리(강동구민회관앞)': 0, '삼각지': 0, '어린이대공원(세종대)': 0, '여의도': 0, '청량리(서울시립대입구)': 0, '천호(풍납토성)': 0, '창신': 0, '복정': 0, '선릉': 0, '하남시청(덕풍·신장)': 0, '새절(신사)': 0, '효창공원앞': 0, '녹사평(용산구청)': 0, '길음': 0, '명동': 0, '까치산': 0, '남구로': 0, '답십리': 0, '남한산성입구(성남법원.검찰청)': 0, '논현': 0, '화곡': 0, '을지로4가': 0, '장한평': 0, '신길': 0, '광명사거리': 0, '온수(성공회대입구)': 0, '신중동': 0}

In [11]:
for i in range(count):
    current = seoulsubDF.iloc[i]
    dict_count_of_people_by_stations[current['역명']] += current['총합']
print(dict_count_of_people_by_stations)

{'신정네거리': 5406924, '충정로(경기대입구)': 7441203, '마들': 6545979, '매봉': 6007569, '오목교(목동운동장앞)': 11433551, '서대문': 9640329, '강동구청': 5344874, '종각': 19213514, '마포': 7267287, '망원': 8008440, '마천': 3767589, '미아사거리': 13812043, '금호': 4020661, '증산(명지대앞)': 5152092, '하계': 9008486, '여의나루': 7903257, '학여울': 1323093, '미사': 8939538, '건대입구': 27248889, '하남검단산': 3378485, '역삼': 26113170, '거여': 5078536, '독바위': 1472534, '안암(고대병원앞)': 6469523, '신금호': 3330658, '구의(광진구청)': 12133484, '수유(강북구청)': 17762898, '동대문': 16437134, '용마산(용마폭포공원)': 3032359, '중곡': 5361896, '신대방삼거리': 7521414, '고속터미널': 34013276, '애오개': 3369189, '성신여대입구(돈암)': 10792567, '우장산': 7440985, '하남풍산': 2268071, '월곡(동덕여대)': 6122805, '춘의': 0, '사당': 34826436, '몽촌토성(평화의문)': 3459706, '까치울': 0, '도곡': 2669011, '장승배기': 4662373, '부천시청': 0, '개롱': 3390568, '한양대': 5659711, '불광': 11295724, '광화문(세종문화회관)': 16559547, '고덕': 5067339, '대치': 6261531, '경복궁(정부서울청사)': 12872556, '상수': 5675516, '신풍': 5822117, '천왕': 5706106, '송파': 4631133, '모란': 2387129, '용두(동대문구청)': 1274479, '장지': 8570283, '김포공항': 4276732, '신흥': 2764590, '신촌': 20060945, '합정': 25113525, '공릉(서울과학기술대)': 6219985, '용답': 1596347, '둔촌동': 4538426, '수서': 9776572, '광나루(장신대)': 6924234, '수진': 2748773, '송정': 3248585, '올림픽공원(한국체대)': 2540578, '문래': 11049145, '숭실대입구(살피재)': 7157174, '산성': 2747389, '내방': 7326563, '신대방': 13134633, '문정': 10335412, '서울역': 35434996, '대청': 5115941, '무악재': 2245725, '당고개': 4763362, '강동': 9195965, '가락시장': 8743300, '청구': 3866434, '성수': 20781129, '버티고개': 1125203, '동묘앞': 9743549, '방배': 8793938, '이촌(국립중앙박물관)': 5357483, '영등포시장': 5720862, '동대입구': 5479354, '잠실(송파구청)': 49384021, '구로디지털단지': 28953037, '양평': 3634056, '회현(남대문시장)': 13609597, '신당': 12151766, '남부터미널(예술의전당)': 15373578, '중화': 5491785, '잠원': 2507660, '발산': 11055852, '상왕십리': 7210774, '도림천': 682609, '봉천': 11909721, '당산': 10123712, '봉화산(서울의료원)': 4458333, '종합운동장': 6943446, '길동': 4264257, '수락산': 6612773, '한성대입구(삼선교)': 7166877, '디지털미디어시티': 7679508, '왕십리(성동구청)': 10331832, '양천구청': 3669243, '고려대(종암)': 4437057, '남성': 5679335, '독립문': 3973373, '시청': 25366419, '강변(동서울터미널)': 16308573, '신정(은행정)': 6308781, '연신내': 17736707, '종로5가': 12858715, '낙성대(강감찬)': 14063557, '강남': 40128362, '태릉입구': 7951833, '응암': 9036385, '가산디지털단지': 20529773, '반포': 3147211, '암사': 9069178, '마장': 2939593, '약수': 8564957, '신용산': 9888601, '을지로3가': 17825161, '서울대입구(관악구청)': 23918508, '미아(서울사이버대학)': 7746880, '방이': 3808247, '충무로': 14665446, '신답': 911046, '도봉산': 5151181, '석촌': 4401254, '옥수': 4786675, '일원': 5354454, '쌍문': 14404610, '구산': 3573818, '석계': 6463488, '개화산': 2933208, '지축': 3334086, '대림(구로구청)': 17650207, '중계': 7236795, '남위례': 3448385, '동대문역사문화공원(DDP)': 18806123, '먹골': 5281343, '청담': 10029202, '상도': 6001486, '신사': 14853698, '강남구청': 8579741, '동작(현충원)': 1098876, '면목': 7796429, '목동': 8731475, '녹번': 7648380, '보문': 3865484, '단대오거리': 6174531, '신도림': 25612882, '장암': 990301, '종로3가': 26849222, '학동': 11726657, '삼성(무역센터)': 27846734, '행당': 3939959, '이태원': 6303980, '방화': 3490484, '강일': 2691224, '광흥창(서강)': 4599265, '화랑대(서울여대입구)': 5436867, '교대(법원.검찰청)': 23419017, '서초': 10894018, '상계': 9657884, '군자(능동)': 13302498, '오금': 4948490, '뚝섬유원지': 5158123, '숙대입구(갈월)': 7367754, '구파발': 10979509, '아현': 5426470, '역촌': 2134896, '철산': 10960783, '잠실나루': 7395459, '압구정': 17049970, '남태령': 669999, '뚝섬': 12221031, '경찰병원': 3706614, '사가정': 8349433, '마포구청': 6991821, '이수': 8069964, '양재(서초구청)': 19103252, '보라매': 3661678, '혜화': 18976969, '총신대입구(이수)': 10238270, '대흥(서강대앞)': 4742264, '월드컵경기장(성산)': 3180957, '창동': 13530744, '명일': 4656744, '홍제': 9132666, '아차산(어린이대공원후문)': 7661385, '신내': 0, '이대': 8643511, '홍대입구': 37322988, '상일동': 7198259, '한강진': 5729120, '삼산체육관': 0, '제기동': 9208336, '신설동': 9060798, '잠실새내': 11853685, '영등포구청': 13173482, '노원': 21426313, '공덕': 16530743, '안국': 13655932, '돌곶이': 4928852, '을지로입구': 23750523, '상월곡(한국과학기술연구원)': 3228710, '마곡': 5550695, '상봉(시외버스터미널)': 8640718, '신림': 28493691, '굽은다리(강동구민회관앞)': 4890873, '삼각지': 6937517, '어린이대공원(세종대)': 8140513, '여의도': 14388795, '청량리(서울시립대입구)': 10783761, '천호(풍납토성)': 18177638, '창신': 1685184, '복정': 4401143, '선릉': 25624286, '하남시청(덕풍·신장)': 3971118, '새절(신사)': 6346294, '효창공원앞': 3620801, '녹사평(용산구청)': 2687413, '길음': 10967586, '명동': 16531390, '까치산': 14406881, '남구로': 7760657, '답십리': 8025015, '남한산성입구(성남법원.검찰청)': 6814521, '논현': 8944142, '화곡': 14281028, '을지로4가': 10266675, '장한평': 9586053, '신길': 2350639, '광명사거리': 10774301, '온수(성공회대입구)': 4927330, '신중동': 0}

In [18]:
seoulsubDF.dtypes[seoulsubDF.dtypes == 'int64']

역번호         int64
06시이전       int64
06-07시간대    int64
07-08시간대    int64
08-09시간대    int64
09-10시간대    int64
10-11시간대    int64
11-12시간대    int64
12-13시간대    int64
13-14시간대    int64
14-15시간대    int64
15-16시간대    int64
16-17시간대    int64
17-18시간대    int64
18-19시간대    int64
19-20시간대    int64
20-21시간대    int64
21-22시간대    int64
22-23시간대    int64
23-24시간대    int64
24시이후       int64
총합          int64
dtype: object

In [17]:
seoulsubDF.dtypes == 'int64'

수송일자        False
호선          False
역번호          True
역명          False
승하차구분       False
06시이전        True
06-07시간대     True
07-08시간대     True
08-09시간대     True
09-10시간대     True
10-11시간대     True
11-12시간대     True
12-13시간대     True
13-14시간대     True
14-15시간대     True
15-16시간대     True
16-17시간대     True
17-18시간대     True
18-19시간대     True
19-20시간대     True
20-21시간대     True
21-22시간대     True
22-23시간대     True
23-24시간대     True
24시이후        True
총합           True
dtype: bool